name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.3.1.app
    
    - uses: actions/checkout@v2
    
    - name: Inatall CocoaPods
      run: gem install cocoapods
    
    - name: Inatall CocoaPods Packages
      run: pod install
      
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
